//URL API
export const OPTIONAL_PRODUCTS_API = 'http://localhost:8882/api/optional-products';
export const OPTIONAL_PRODUCTS_SLIDE_SHOW = '';

//Actions

export const FETCH_OPTIONAL_PRODUCTS = 'FETCH_OPTIONAL_PRODUCTS';
export const RECEIVE_OPTIONAL_PRODUCTS = 'RECEIVE_OPTIONAL_PRODUCTS';
export const ERROR_IN_FETCH_OPTIONAL_PRODUCTS = 'ERROR_IN_FETCH_OPTIONAL_PRODUCTS';